package main

import (
	"embed"
	"io/fs"

	"log"
	"net/http"
)

//go:embed all:frontend/dist
var viteFS embed.FS

func main() {

	// Root at the `dist` folder generated by the vite app.
	distFS, err := fs.Sub(viteFS, "frontend/dist")

	if err != nil {
		log.Fatal(err)
	}
	// Create a new request multiplexer
	// Take incoming requests and dispatch them to the matching handlers
	mux := http.NewServeMux()

	log.Println("Configuring...")
	mux.Handle("/", http.FileServer(http.FS(distFS)))

	// Run the server
	server := &http.Server{
		Addr:    ":8080",
		Handler: mux,
	}
	log.Println("Listening...")
	server.ListenAndServe() // Run the http server

}
